services:

  firebase:
    image: baby-equipment-exchange-image
    build:
      context: .
      target: firebase
    command: firebase emulators:start --only functions
    environment:
      - FIREBASE_TOKEN
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/functions/node_modules
    ports:
      # https://firebase.google.com/docs/emulator-suite/install_and_configure#port_configuration
      - "4000:4000" # Emulator Suite UI
      - "5001:5001" # Cloud Functions

  functions:
    image: baby-equipment-exchange-image
    build:
      context: .
      target: functions
    working_dir: /usr/src/app/functions
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/functions/node_modules
    command: npm run build:watch
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS
      - NODE_ENV=development
    depends_on:
      - firebase

  server-equipment-exchange:
    image: baby-equipment-exchange-image
    build:
      context: .
      target: app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/functions/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
